[build]
  base = "frontend"
  publish = "build"
  command = "npm run build"

[build.environment]
  CI = "false"
  GENERATE_SOURCEMAP = "false"

[[redirects]]
  from = "/api/*"
  to = "https://updated-2-0.vercel.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200